name: elcal
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/julemand101/elcal

environment:
  sdk: ^3.0.0

dependencies:
  ical: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
